apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage-class
  namespace: kube-system
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01cfe0691db892955
  directoryPerms: "700"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-app-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${SHARED_APP_DATA_STORAGE_CLASS}
  resources:
    requests:
      storage: 100Mi
