apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blob-gateway-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: blob-gateway-service
    k8s.kuboard.cn/workload: blob-gateway-service
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-http-redirect-https-testing@kubernetescrd,
      kube-system-strip-blob-gateway-prefix@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - '*.testnet-conway.blobgateway.com'
        - testnet-conway.blobgateway.com
      secretName: testnet-conway-blobgateway-com-tls
  rules:
    - host: api.testnet-conway.blobgateway.com
      http: &http_rules
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blob-gateway-service
                port:
                  number: 8080
